<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFErnwN2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFErnwN2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFErnwN2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFErnwN2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFErnwN2\App_KernelDevDebugContainer([
    'container.build_hash' => 'FErnwN2',
    'container.build_id' => 'dd8b9024',
    'container.build_time' => 1710864114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFErnwN2');
