<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzMnF2R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzMnF2R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGzMnF2R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGzMnF2R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGzMnF2R\App_KernelDevDebugContainer([
    'container.build_hash' => 'GzMnF2R',
    'container.build_id' => 'd0c9a0fb',
    'container.build_time' => 1710863010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzMnF2R');
